Add paginated results to Categories
alkemyTech/OT300-server pull request #136
Opened 2022-10-07 01:47 UTC by DnTo

![image](https://user-images.githubusercontent.com/5188401/194448876-6a9bb1d7-590f-49a6-9b90-a7d42c17c0d8.png)
![image](https://user-images.githubusercontent.com/5188401/194448907-c8f3d594-7cf8-42d8-8b8b-bb6a4daacb6f.png)
![image](https://user-images.githubusercontent.com/5188401/194448940-6fffcf7a-dfb6-4daf-93bf-719805e8403e.png)
![image](https://user-images.githubusercontent.com/5188401/194448976-aa4f49a5-4762-4d29-9fe5-365d9b95c8cd.png)
![image](https://user-images.githubusercontent.com/5188401/194449011-fc9c40a0-c72d-4326-b527-09257ff00e38.png)
![image](https://user-images.githubusercontent.com/5188401/194449079-d1e0a813-ef2d-4f96-bcc1-790d36d6fa1f.png)

2022-10-07 01:49 UTC, DnTo commented
![image](https://user-images.githubusercontent.com/5188401/194449239-e8552c2a-6058-4c9d-862b-2ce372fbdcf4.png)

2022-10-11 01:47 UTC, emmanuelranone requested changes
En general bien, solo que lo que serían los datos de la paginación se recomienda que esté al principio y luego los datos de la entidad...
También Estaría bueno agregar la página actual y la cantidad de páginas totales de acuerdo al tamaño de página que manejamos.

2022-10-11 13:40 UTC, DnTo commented
![image](https://user-images.githubusercontent.com/5188401/195106515-47a57622-5e0e-41cb-848d-cfbdc6c55de9.png)

2022-10-11 17:47 UTC, emmanuelranone approved these changes
Bárbaro !

2022-10-11 17:47 UTC, merged