Update Testimonial
alkemyTech/OT300-server pull request #137
Opened 2022-10-07 16:37 UTC by MatGP20

Added Controller, Business, Mapper and DTO for Testimonial Update.

And if a variable is empty or null in the update, keep the data of DB.

![image](https://user-images.githubusercontent.com/78388067/194603882-96437850-8ca1-4837-9ffb-59740bc732bd.png)

2022-10-07 19:10 UTC, DnTo requested changes

2022-10-07 19:10 UTC, DnTo commented on OngProject/Controllers/MemberController.cs
> +        [Authorize]
Un usuario estandar podria borrar un Testimony

2022-10-07 19:10 UTC, DnTo commented on OngProject/Controllers/TestimonialController.cs
> +        [Authorize]
Solo el admin puede crear un testimonio

2022-10-07 23:54 UTC, MatGP20 commented on OngProject/Controllers/TestimonialController.cs
> +        [Authorize]
En la story de creación de Testimonios que me toco en el sprint pasado no dice nada de que sean solo para la creación de los administradores.

2022-10-08 03:23 UTC, MatGP20 commented
added changes in testimonial controller authorization

2022-10-11 01:43 UTC, emmanuelranone approved these changes

2022-10-11 01:43 UTC, merged