Agregar paginación a Novedades
alkemyTech/OT300-server pull request #147
Opened 2022-10-11 13:55 UTC by matute1910

2022-10-11 13:57 UTC, matute1910 commented
![PageNewsOk](https://user-images.githubusercontent.com/78965121/195111014-43275fea-0be8-48fc-90ea-b13dba86a184.png)

2022-10-11 17:49 UTC, emmanuelranone requested changes
Fijate que se modifico la clase de paginación, para que primero devuelva los datos del paginado y después la lista. 
Fijate si tu desarrollo sigue funcionando y enviá capturas neuvas.

2022-10-11 19:18 UTC, matute1910 commented
![PageNews](https://user-images.githubusercontent.com/78965121/195179763-23f9ba05-a19a-43cb-a4b2-444fbc85829a.png)

2022-10-12 12:39 UTC, emmanuelranone approved these changes

2022-10-12 12:39 UTC, merged