Adds RoleRepository.cs, RoleService.cs and RoleController.cs
alkemyTech/OT300-server pull request #20
Opened 2022-09-17 11:05 UTC by Geraldsonp

Aplicando el patron Unit of Work, crear el repositorio y servicio base, con las operaciones getAll, getById, insert, delete y update

2022-09-17 19:53 UTC, emmanuelranone requested changes
No estaría mal, pero no respeta nuestrar arquitectura. Lo hablamos por slack

2022-09-18 10:11 UTC, Geraldsonp commented
Changes done

2022-09-18 22:20 UTC, emmanuelranone requested changes
Apruebo el pr, pero estás haciendo más cosas de lo pedido. Eso no está bien, porque se utiliza tiempo de un recurso en otra cosa. Más adelante vamos a trabajar en los diferentes endpoints

2022-09-18 22:21 UTC, emmanuelranone approved these changes

2022-09-18 22:21 UTC, merged