Delete Category non cascade delete
alkemyTech/OT300-server pull request #94
Opened 2022-09-29 23:45 UTC by DnTo

2022-09-29 23:59 UTC, emmanuelranone requested changes
Faltaria adjuntar capturas del funcionamiento

2022-09-30 00:16 UTC, DnTo commented
estan en jira

2022-09-30 00:19 UTC, DnTo commented
![image](https://user-images.githubusercontent.com/5188401/193163978-bfd75d2e-ab23-4ce2-bb6f-71756df25aba.png)
![image](https://user-images.githubusercontent.com/5188401/193163996-1883df61-4221-4499-b781-8b2b69337f00.png)
![image](https://user-images.githubusercontent.com/5188401/193164006-8d1210fb-d88c-409a-aef7-564376f4d535.png)
![image](https://user-images.githubusercontent.com/5188401/193164026-cecf3222-63b3-47b2-86c3-60dea0d5614c.png)

2022-09-30 11:43 UTC, emmanuelranone approved these changes

2022-09-30 11:43 UTC, merged